modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId = "elementalcombat_weaponry" #mandatory
version = "1.0" #mandatory

displayName = "Elemental Combat - Weaponry" #mandatory
issueTrackerURL="https://github.com/Tavi007/ElementalCombat-Weaponry/issues" #optional
logoFile = "Icon.png" #optional. A file name (in the root of the mod JAR) containing a logo for display
credits = "Thanks goes to the Forge Forum" #optional
authors = "Tavi007" #optional

description= "This mod showcases the fun stuff, one can do with the Elemental Combat API."

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.elementalcombat_weaponry]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.elementalcombat_weaponry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
#[[dependencies.elementalcombat_weaponry]]
#    modId="elementalcombat"
#    mandatory=true
#    versionRange="[1.1.1,)"
#    ordering="NONE"
#    side="BOTH"
